// File generated by FlutterFire CLI for Firebase project "tawali-2ded4".
// Do not manually edit this file.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_fhbkgr47pTANRLa5pzFMHZ1s4S9ipsk',
    appId: '1:945949606458:android:1a1adf4233cfcf8eabeb03',
    messagingSenderId: '945949606458',
    projectId: 'tawali-2ded4',
    storageBucket: 'tawali-2ded4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_fhbkgr47pTANRLa5pzFMHZ1s4S9ipsk',
    appId: '1:945949606458:android:1a1adf4233cfcf8eabeb03',
    messagingSenderId: '945949606458',
    projectId: 'tawali-2ded4',
    storageBucket: 'tawali-2ded4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_fhbkgr47pTANRLa5pzFMHZ1s4S9ipsk',
    appId: '1:945949606458:android:1a1adf4233cfcf8eabeb03',
    messagingSenderId: '945949606458',
    projectId: 'tawali-2ded4',
    storageBucket: 'tawali-2ded4.firebasestorage.app',
    iosBundleId: 'com.mualimx.tawali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_fhbkgr47pTANRLa5pzFMHZ1s4S9ipsk',
    appId: '1:945949606458:android:1a1adf4233cfcf8eabeb03',
    messagingSenderId: '945949606458',
    projectId: 'tawali-2ded4',
    storageBucket: 'tawali-2ded4.firebasestorage.app',
    iosBundleId: 'com.mualimx.tawali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4_fhbkgr47pTANRLa5pzFMHZ1s4S9ipsk',
    appId: '1:945949606458:android:1a1adf4233cfcf8eabeb03',
    messagingSenderId: '945949606458',
    projectId: 'tawali-2ded4',
    storageBucket: 'tawali-2ded4.firebasestorage.app',
  );
}